insert into public.products (slug, name, material, price_cents, category, description, specs, icon_key, sort) values
('custom-enclosure','Custom Enclosure','PETG',2400,'Enclosures','A snap-fit project enclosure sized and vented to your electronics. We print in durable PETG for chemical and impact resistance, ideal for prototypes, IoT devices, and control boxes.','{"Material":"PETG","Layer height":"0.2mm","Infill":"20% gyroid","Lead time":"3-5 days","Finish":"Matte, sanded seams"}','enclosure',1),
('mounting-bracket','Mounting Bracket','PLA+',1200,'Mechanical','A rigid L-bracket for shelving, sensors, or panel mounts. PLA+ gives a clean finish and strong layer adhesion for light-to-medium structural loads.','{"Material":"PLA+","Layer height":"0.16mm","Infill":"30%","Lead time":"3-5 days","Finish":"Standard"}','bracket',2),
('prototype-shell','Prototype Shell','ABS',1800,'Prototyping','A functional prototype housing printed in ABS for heat resistance and post-processing (sanding, gluing, acetone smoothing). Great for early-stage product testing.','{"Material":"ABS","Layer height":"0.2mm","Infill":"25%","Lead time":"3-5 days","Finish":"Paint-ready"}','shell',3),
('resin-detail-part','Resin Detail Part','Resin',3200,'Resin','High-resolution SLA resin part for miniatures, jewelry masters, or fine mechanical details. Layer resolution down to 0.05mm captures crisp edges and fine text.','{"Material":"Standard resin","Layer height":"0.05mm","Lead time":"4-6 days","Finish":"Cured, supports removed"}','detail',4),
('cable-organiser','Cable Organiser','TPU',800,'Accessories','A flexible TPU cable clip that snaps onto desk edges or panels. Durable, bendable, and resistant to cracking over repeated use.','{"Material":"TPU 95A","Layer height":"0.2mm","Infill":"40%","Lead time":"3-5 days","Finish":"Standard"}','cable',5),
('gear-assembly','Gear Assembly','Nylon',4500,'Mechanical','A precision-fit gear set printed in Nylon for wear resistance and low-friction operation. Suited for functional mechanisms and light-duty drivetrains.','{"Material":"Nylon (PA12)","Layer height":"0.16mm","Infill":"40%","Lead time":"5-7 days","Finish":"Standard"}','gear',6),
('desk-organizer','Desk Organizer','PLA+',1500,'Accessories','A modular desk tray for pens, cables, and small tools. Stackable design, printed in PLA+ for a crisp, clean finish.','{"Material":"PLA+","Layer height":"0.2mm","Infill":"15%","Lead time":"3-5 days","Finish":"Standard"}','tray',7),
('phone-stand','Phone Stand','PETG',1000,'Accessories','An adjustable-angle phone stand for desks and counters. PETG construction resists warping and everyday wear.','{"Material":"PETG","Layer height":"0.2mm","Infill":"25%","Lead time":"3-5 days","Finish":"Standard"}','stand',8);
